version: '2'
services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    build:
      context: ./build/docker/mysql
      dockerfile: ./Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    build:
      context: ./build/docker/redis
      dockerfile: ./Dockerfile
    hostname: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:
